services:
  postgres:
    image: postgres:15.5
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    restart: on-failure
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-postgres}", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:7.0.5
    ports:
      - 8081:8081
    restart: on-failure
    volumes:
      - mongo:/data/db

volumes:
  postgres:
  mongo:
