drop database IF EXISTS bd_sistema_bancario;
create database bd_sistema_bancario;
\c bd_sistema_bancario;
create table tabela1 (cod integer);
create table tabela2 (cod integer);
create table tabela3 (cod integer);
create table tabela4 (cod integer);
create table tabela5 (cod integer);
create table cliente (nome_cliente text, cidade_cliente text, endereco_cliente text);
create table emprestimo(numero_emprestimo integer, nome_agencia text, valor real);
create table conta(numero_conta integer, nome_agencia text, saldo real);
create table agencia(nome_agencia text, cidade_agencia text, depositos real);
drop table tabela1;
drop table tabela2;
drop table tabela3;
drop table tabela4;
drop table tabela5;
alter table cliente rename to tbl_cliente;
alter table emprestimo rename to tbl_emprestimo;
alter table conta rename to tbl_conta;
alter table agencia rename to tbl_agencia;
alter table tbl_cliente add column idade integer;
alter table tbl_cliente add column cpf integer;
alter table tbl_agencia rename column cidade_agencia to endereco_agencia;
create schema rodrigo;